name: Scheduled Test Run

on:
  schedule:
    - cron: '22 9 * * *'  # Every day at 2:52 PM IST (9:22 AM UTC)
  workflow_dispatch:      # Enables manual trigger

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      - name: Run tests and generate HTML report
        run: |
          mkdir -p test_logs
          pytest --html=test_logs/test_log.html --self-contained-html

      - name: Upload test report as artifact
        uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: test_logs/test_log.html


      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ GitHub Action Test Report"
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          secure: true
          attachments: test_logs/test_log.html
          body: |
            Hello,

            Your scheduled test run has completed.
            Please find the attached HTML report.

            Regards,  
            GitHub Actions
