name: Scheduled Test Run

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes (UTC)
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      - name: Run tests and generate HTML report
        run: |
          mkdir -p test_logs
          pytest --html=test_logs/test_log.html --self-contained-html

      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ GitHub Action Test Report"
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          secure: true
          attachments: test_logs/test_log.html
          body: |
            Hello,

            Your scheduled test run has completed.
            Please find the attached HTML report.

            Regards,  
            GitHub Actions

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Copy logs to root folder
        run: |
          mkdir -p pushed_logs
          cp logs/*.log pushed_logs/

      - name: Commit and push logs
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git fetch
          git checkout main
          git pull
          cp -r pushed_logs/* .
          git add *.log
          git commit -m "🔄 Add test log from scheduled run - $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
